django_connect/auth/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('',
	url(r'^welcome/$', 'auth.views.welcome', name='welcome'),
    url(r'^login/$', 'auth.views.login', name='login'),
    url(r'^logout/$', 'auth.views.logout', name='logout'),
	url(r'^logged_out/$', 'auth.views.logged_out', name='logged_out'),
)

django_connect/django_connect/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView


admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', 'auth.views.welcome', name='home'), # change this to something else that redirects to welcome with if not logged in

    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^auth/', include('auth.urls', namespace='auth', app_name='auth')),
    url(r'^users/', include('users.urls', namespace='users', app_name='users')),

    # django all access
    url(r'^connect/', include('connect.urls')),
    # django admin
    url(r'^admin/', include(admin.site.urls)),
)

# Serve static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    
    import debug_toolbar
    
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

django_connect/templates/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_media_prefix as MEDIA_PREFIX %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}django_connect{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/django_connect.css' %}" rel="stylesheet">

    <!-- Use this to quickly test CSS changes in a template,
        then move to django_connect.css -->
    {% block extra_css %}{% endblock extra_css %}
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">django connect</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'users:me' %}">Me</a></li>
            <li><a href="{% url 'account:settings' %}">Settings</a></li>
            <li><a href="{% url 'auth:login' %}">Login</a></li>
            <li><a href="{% url 'auth:logout' %}">Logout</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
      {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
      {% endif %}
      <h1>{% block page_title %}Example Base Template{% endblock page_title %}</h1>

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/django_connect.js' %}"></script>

    {% block extra_js %}{% endblock extra_js %}
  </body>
</html>